FROM centos:centos6
RUN yum update -y && yum -y install wget && wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm && rpm -ivh epel-release-6-8.noarch.rpm
RUN yum update -y && yum -y install xorg-x11-server-Xorg fontconfig binutils findutils mesa-libEGL.x86_64 libSM.x86_64 libXinerama libXrandr libXcursor libXcomposite
