FROM ubuntu:14.04
RUN apt-get update && apt-get install -y software-properties-common libX11-6 libegl1-mesa libgl1-mesa-glx expat strace bsdtar binutils fontconfig libsm6 dbus
RUN dbus-uuidgen > /etc/machine-id